repository_type: pipeline
nf_core_version: "2.14.1"
lint:
  files_unchanged:
    - assets/nf-core-variantmtb_logo_light.png
    - docs/images/nf-core-variantmtb_logo_light.png
    - docs/images/nf-core-variantmtb_logo_dark.png
