repository_type: pipeline
lint:
  files_unchanged:
    - assets/nf-core-variantmtb_logo_light.png
    - docs/images/nf-core-variantmtb_logo_light.png
    - docs/images/nf-core-variantmtb_logo_dark.png
